name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Build
      run: |
        GOARCH=amd64 go build -o proxy_amd64
        GOARCH=arm64 go build -o proxy_arm64
        GOARCH=arm GOARM=7 go build -o proxy_armv7
      env: 
        CGO_ENABLED: 0 # statically link
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-results
        path: proxy_*
   
      
